// SPDX-License-Identifier: MIT
// Copyright 2026 Seclave AB

//! Run the shared conformance vectors against this implementation.
//!
//! The vectors are generated by the Python implementation (the reference,
//! validated against real hardware); passing them is what makes this crate a
//! port rather than a lookalike. See vectors/README.md at the repo root.

use seclave::{
    build_frame, decode_field_span, decode_int, encode_field, encode_int, parse_response,
    DecodeError,
};
use serde_json::Value;

fn vectors() -> Value {
    serde_json::from_str(include_str!("../../../vectors/protocol.json")).unwrap()
}

fn unhex(hex: &str) -> Vec<u8> {
    assert!(hex.len().is_multiple_of(2), "odd hex string: {hex}");
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

fn cases<'a>(root: &'a Value, key: &str) -> &'a Vec<Value> {
    root[key]
        .as_array()
        .unwrap_or_else(|| panic!("no {key} array"))
}

#[test]
fn integers() {
    let root = vectors();
    for case in cases(&root, "integers") {
        let value = case["value"].as_u64().unwrap() as u16;
        let encoded = match case["encoded"].as_str() {
            Some(hex) => {
                let encoded = unhex(hex);
                assert_eq!(encode_int(value), encoded, "encode {value}");
                encoded
            }
            // Non-canonical encodings: decode-only.
            None => unhex(case["encoded_alternative"].as_str().unwrap()),
        };
        assert_eq!(
            decode_int(&encoded, 0),
            Ok((value, encoded.len())),
            "decode {value}"
        );
    }
}

#[test]
fn integer_errors() {
    let root = vectors();
    for case in cases(&root, "integer_errors") {
        let raw = unhex(case["encoded"].as_str().unwrap());
        assert!(
            matches!(decode_int(&raw, 0), Err(DecodeError::BadEscapeLength(_))),
            "expected rejection of {raw:02x?}"
        );
    }
}

#[test]
fn integer_incomplete() {
    let root = vectors();
    for case in cases(&root, "integer_incomplete") {
        let raw = unhex(case["encoded"].as_str().unwrap());
        assert_eq!(
            decode_int(&raw, 0),
            Err(DecodeError::NeedMore),
            "expected NeedMore on {raw:02x?}"
        );
    }
}

#[test]
fn fields() {
    let root = vectors();
    for case in cases(&root, "fields") {
        let payload = unhex(case["payload"].as_str().unwrap());
        let encoded = unhex(case["encoded"].as_str().unwrap());
        assert_eq!(encode_field(&payload), encoded);
        let ((start, end), next) = decode_field_span(&encoded, 0).unwrap();
        assert_eq!(&encoded[start..end], &payload[..]);
        assert_eq!(next, encoded.len());
    }
}

#[test]
fn frames() {
    let root = vectors();
    for case in cases(&root, "frames") {
        let payload = unhex(case["payload"].as_str().unwrap());
        let framed = unhex(case["framed"].as_str().unwrap());
        assert_eq!(build_frame(&payload).unwrap(), framed);
    }
    for case in cases(&root, "frame_errors") {
        let length = case["payload_length"].as_u64().unwrap() as usize;
        assert!(
            build_frame(&vec![0x71; length]).is_err(),
            "expected refusal of length {length}"
        );
    }
}

#[test]
fn responses() {
    let root = vectors();
    for case in cases(&root, "responses") {
        let raw = unhex(case["bytes"].as_str().unwrap());
        let field_count = case["field_count"].as_u64().unwrap() as usize;
        let parsed = parse_response(&raw, field_count).unwrap();
        if case["incomplete"].as_bool().unwrap_or(false) {
            assert!(parsed.is_none(), "expected incomplete: {case}");
            continue;
        }
        let response = parsed.unwrap_or_else(|| panic!("expected complete: {case}"));
        assert_eq!(response.status, case["status"].as_u64().unwrap() as u16);
        let fields: Vec<String> = response
            .fields
            .iter()
            .map(|(start, end)| {
                raw[*start..*end]
                    .iter()
                    .map(|byte| format!("{byte:02x}"))
                    .collect()
            })
            .collect();
        let expected: Vec<&str> = case["fields"]
            .as_array()
            .unwrap()
            .iter()
            .map(|field| field.as_str().unwrap())
            .collect();
        assert_eq!(fields, expected, "{case}");
    }
}
